### ISSUE TITLE
Putting in a README.

### ISSUE THREAD

**Issue by oakenduck** [blinkakawize1/text-based-rpg#1]
I'd really like to check out your project, as I'm working on a **TBRPG** of my own, but I'm not sure how to use your program. It'd be great if you placed a `README.md` file, detailing how to start it and use it. That would make it much easier to understand your code, and even help if necessary. Thanks.

**Comment by blinkakawize1** [comment]
> I'd really like to check out your project, as I'm working on a **TBRPG** of my own, but I'm not sure how to use your program. It'd be great if you placed a `README.md` file, detailing how to start it and use it. That would make it much easier to understand your code, and even help if necessary. Thanks.

I am going to add one now. Thanks. I look forward to collaborating with you in the future.
